title:  "StudyML"
tagline: "Machine Learning Portal"
description:

# Authors documented under _data

# Change to true for Disqus comments
disqus:
  comments: true
  disqus_shortname: 'vikasjain91'

menu:
- {name: 'ML Algorithms', folder: 'pages', file: 'ML.html'}
- {name: 'Learn R', folder: 'pages', file: 'rprogramming.html'}
- {name: 'Learn Python', folder: 'pages', file: 'python.html'}
- {name: 'Deep Learning', folder: 'pages', file: 'deeplearning.html'}
- {name: 'AI', folder: 'pages', file: 'ai.html'}
- {name: 'Contact Me', folder: 'pages', file: 'contact.html'}

social:
- {icon: 'twitter', link: 'https://twitter.com/vikasjain_91'}
- {icon: 'facebook', link: 'https://www.facebook.com/vikasjain91'}
- {icon: 'instagram', link: 'https://instagram.com/vikasjain_91'}
- {icon: 'envelope', link: 'mailto:vikasjain081291@live.com'}
- {icon: 'rss-square', link: 'feed.xml'}

google-ID: 'UA-110688521-1'

# Available social icons are powered by Font Awesome, so you can use any icon that they offer
